USE [BENZINEtanks]
GO

/****** Object:  Table [dbo].[T1]    Script Date: 26.11.2020 14:31:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T1](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductDensity_NUMERICID] [varchar](64) NULL,/*плотность бензола*/
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductDensity_VALUE] [char](64) NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductDensity_TIMESTAMP] [datetime] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductDensity_QUALITY] [smallint] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS15_T1Density_NUMERICID] [varchar](64) NULL,/*плотность к15 гр*/
	[SIEMENS1200_PLC1_DATA_TANKS15_T1Density_VALUE] [char](64) NULL,
	[SIEMENS1200_PLC1_DATA_TANKS15_T1Density_TIMESTAMP] [datetime] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS15_T1Density_QUALITY] [smallint] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductLevel_NUMERICID] [varchar](64) NULL,/*уровень безола мм*/
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductLevel_VALUE] [char](64) NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductLevel_TIMESTAMP] [datetime] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductLevel_QUALITY] [smallint] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductMass_NUMERICID] [varchar](64) NULL,/*масса бензола кг*/
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductMass_VALUE] [char](64) NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductMass_TIMESTAMP] [datetime] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductMass_QUALITY] [smallint] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductVolume_NUMERICID] [varchar](64) NULL,/*обьем бензола*/
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductVolume_VALUE] [char](64) NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductVolume_TIMESTAMP] [datetime] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1ProductVolume_QUALITY] [smallint] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS15_T1Volume_NUMERICID] [varchar](64) NULL,/*обьем бензола к 15*/
	[SIEMENS1200_PLC1_DATA_TANKS15_T1Volume_VALUE] [char](64) NULL,
	[SIEMENS1200_PLC1_DATA_TANKS15_T1Volume_TIMESTAMP] [datetime] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS15_T1Volume_QUALITY] [smallint] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1Temperature_NUMERICID] [varchar](64) NULL,/*средн€€ температура в емкости*/
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1Temperature_VALUE] [char](64) NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1Temperature_TIMESTAMP] [datetime] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1Temperature_QUALITY] [smallint] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1TotalLevel_NUMERICID] [varchar](64) NULL,/*общий уровень жидкости в емкости*/
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1TotalLevel_VALUE] [char](64) NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1TotalLevel_TIMESTAMP] [datetime] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1TotalLevel_QUALITY] [smallint] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1WaterLevel_NUMERICID] [varchar](64) NULL,/*уровень воды в емкости*/
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1WaterLevel_VALUE] [char](64) NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1WaterLevel_TIMESTAMP] [datetime] NULL,
	[SIEMENS1200_PLC1_DATA_TANKS_Tank1WaterLevel_QUALITY] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


